### ISSUE TITLE
virtual assistant: icon not always showing up

### ISSUE THREAD

**Issue by pkabus** [CristoferSoler/Seel-17-18#197]

**Comment by pkabus** [comment]
![virtualassistant.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f706a3b5096a0012cc9f93/125516c66e82c728ace21e0d46fe9d88379782a58efaac4ab749f19a3d046b313916ac217586f76ae5002e58095918f941585612f8ad8d2ea6b63f228f550becd86f4d68d47f40f2ecdd42e64bef62994597b7bb804dc5e93b25e58f87473e19021b9bb2.PNG)

**Comment by j0na1han** [comment]
i hear from this bug the first time. When did it happen?

**Comment by pkabus** [comment]
I fixed it. You just have to use src={% static "bsi/images/wizard.png" %} in html. before you used an relative path and this fails in some cases.
