### ISSUE TITLE
edit an article without beeing logged in by accessing: (works even on BSI pages!!!)

### ISSUE THREAD

**Issue by j0na1han** [CristoferSoler/Seel-17-18#209]
e.g. http://it-gs.ziik.tu-berlin.de:8000/uga/fire-estinguisher/edit/

**Comment by andisadewi** [comment]
how do we edit the bsi pages? with which url?

**Comment by j0na1han** [comment]
i don't know. I have read the comments from the Ana Group. Maybe on Monday they'll be able to give us what they wanted.
