### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by Multiflux** [CristoferSoler/Seel-17-18#22]

**Comment by circle-ish** [comment]
Issues:
-can guests see the forum or registered users only?

**Comment by circle-ish** [comment]
originally from Chris:
- have polls in the forum; could be used when there are no mods to ban users (in case of hatespeech in example) by community vote

**Comment by majdhasan** [comment]
Forum as its defined won't be implemented, therefore we will include different types of user interaction. see further issues..
