### ISSUE TITLE
Treeview redirects to different domain

### ISSUE THREAD

**Issue by pkabus** [CristoferSoler/Seel-17-18#235]

**Comment by andisadewi** [comment]
this problem came because of a merging problem back on tuesday. All server-specific paths are copied to django-wiki branch. So everyone please update the links to your own specific path (in bsiTreeLinks.txt and pathlist.txt) by setting the site domain to localhost and then running the treeview_importer.py. Then don't commit them to avoid more problem :)

**Comment by andisadewi** [comment]
on the server itself everything is fine :)

**Comment by pkabus** [comment]
in the init() method someone set the site domain to it-gs.ziik.tu-berlin.de:8000, thats of course not a good idea

**Comment by pkabus** [comment]
and thats another reason why the admin area should exist with more than only user/group and update settings. its the only chance for superusers to configure the application.

**Comment by andisadewi** [comment]
yes i think that was because of the merging on tuesday which shouldn't be the case. You can change it back to localhost. thanks :)

**Comment by pkabus** [comment]
no i think its better to not set it there

**Comment by andisadewi** [comment]
we could probably include site, archive and info page configuration (+ notification/subscription if we want to include them later). But more than that i think is unnecessary. What do you think should be included?

**Comment by andisadewi** [comment]
but i still think superusers should be admins. and then there are mods who can review ugas and the infopage

**Comment by pkabus** [comment]
superusers are admins

**Comment by pkabus** [comment]
but not the other way around

**Comment by andisadewi** [comment]
"no i think its better to not set it there" -> i put the site config back to admin panel. so we can set there. i dont remember if i put the commit in django-wiki or final branch though

**Comment by andisadewi** [comment]
"superusers are admins" okay that is good :)

**Comment by pkabus** [comment]
i think we should register most of the tables in the admin area (not like it is now). but for the admin control panel we will only show user settings and the update button

**Comment by andisadewi** [comment]
what is the difference between admin area and admin control panel?
only superusers have admin area and all admins have admin control panel?

**Comment by andisadewi** [comment]
im getting a headache thinking about admin and mods haha

**Comment by pkabus** [comment]
yes. "admin area" -> /admin

**Comment by andisadewi** [comment]
okay i get it now :)
