### ISSUE TITLE
Research Wiki

### ISSUE THREAD

**Issue by circle-ish** [CristoferSoler/Seel-17-18#33]

**Comment by circle-ish** [comment]
-how does wikipedia actually work? what features does it have? how do they play out behind the scenes?
-blog posts about why certain design decision were taken?
-what user roles do they have?
-how does the forum work? what purpose does it have?
-polls, bans

**Comment by Multiflux** [comment]
Voting Highest Wikipedia Court: https://de.wikipedia.org/wiki/Wikipedia:Schiedsgericht/Wahl

**Comment by aliagbaria** [comment]
Ergebnisse aus der Recherche:

1: Wikipedia stellt sich gegen forums:   
Wikipedia ist kein allgemeines Diskussionsforum und kein Chat-Raum. Als Alternative bietet Wikipedia die Artikel-Diskussionsseiten (Talk Pages) an. Diese Talk pages dienen der Verbesserung von Artikeln, nicht dem Austausch persönlicher Betrachtungen zum Artikelthema.

2. Schiedsgericht : 
Die Zuständigkeit des Schiedsgerichts ist auf folgende Fälle beschränkt:
1) kommunikative Auseinandersetzungen zwischen Benutzern (persönliche Angriffe)
2 )Auseinandersetzungen um Adminfunktionen.
3) wiederholte und vorsätzliche Verstöße gegen Wikipedia-Grundsätze (NPOV, Was Wikipedia nicht ist, Theoriefindung, Urheberrechte beachten)

**Es gibt zwei Wahltermine pro Jahr (im Mai und November). Zu diesen Terminen werden jeweils fünf Schiedsrichter für ein Jahr gewählt.
Ein Benutzer ist wahlberechtigt, wenn er insgesamt mindestens 400 Bearbeitungen getätigt hat  und seine erste Bearbeitung mindestens 4 Monate vor Beginn der Wahl erfolgte.
