### ISSUE TITLE
[Wizard] research word confidence calculation in google

### ISSUE THREAD

**Issue by CristoferSoler** [CristoferSoler/Seel-17-18#49]

**Comment by ArmineMik** [comment]
https://www.google.com/patents/US6269188

**Comment by ArmineMik** [comment]
http://eprints.rclis.org/12736/1/Rankingverfahren.pdf

**Comment by ArmineMik** [comment]
https://books.google.de/books?id=JxQlBgAAQBAJ&pg=PA62&lpg=PA62&dq=gewichtung+von+worten+in+suchmaschinen&source=bl&ots=oMD4hxes2g&sig=ya1UfNiLS7vf7BTl9A337wwtYAo&hl=de&sa=X&ved=0ahUKEwier7OiqPbXAhWDcRQKHZXcAQsQ6AEIMjAC#v=onepage&q=gewichtung%20von%20worten%20in%20suchmaschinen&f=false S.62  Proximity verfahren. Wortfolge mit kurzer Entfernung als relevanter erkannt, als Wortfolge mit größere Entfernung zu einander.

**Comment by ArmineMik** [comment]
https://de.wikipedia.org/wiki/Within-document_Frequency

**Comment by ArmineMik** [comment]
https://books.google.de/books?id=uW_pBQAAQBAJ&pg=PA373&lpg=PA373&dq=gewichtung+von+worten+in+dokument&source=bl&ots=BWVrWozU8P&sig=6DTFa7TYNMx3aE7p5D273IUgbYc&hl=de&sa=X&ved=0ahUKEwjQ-v7Gq_bXAhUJvxQKHb-YBYEQ6AEIOzAE#v=onepage&q=gewichtung%20von%20worten%20in%20dokument&f=false
S.373,

**Comment by ArmineMik** [comment]
https://karlkratz.de/onlinemarketing-blog/seo-keyword-density/
