### ISSUE TITLE
[Label] vote change when copying articles

### ISSUE THREAD

**Issue by circle-ish** [CristoferSoler/Seel-17-18#70]
1) put in requirements: what happens to votes when an article is re-linked during an update? Do they stay or are they set to zero?

2) what happens when an article was not re-linked; gets pushed to the archive; but later is copied (in whatever way) back to the wiki? How are the votes?

((( in case that articles that link to articles are not considered during an update (see minutes [BSI] 11/30) : 3) articles that link to articles and that are not archived could be out of date; if they retain their high voting score it would be a page marked as helpful that actually should be in the archive )))

**Comment by CristoferSoler** [comment]
1. they stay
2. its a new article (so no votes)
