### ISSUE TITLE
Rebuild importer

### ISSUE THREAD

**Issue by pkabus** [CristoferSoler/Seel-17-18#88]

**Comment by lTanbari** [comment]
Import the BSI kompendium articles 2018 in the database has two cases:
1- initial importing (for the first time) "done"
         - Build new database schema concept
         - Modify the database schema
         - Test the new crawler and translator
         - Modify the comparator depending on the new crawler and translator
         - Modify the old version of the importer 
        - Add links to the tree view items
        - Append the cross-reference relation to the articles without assigning links to it.

2- Update the BSI kompendium "done"
      - Check the updated articles using the comparator
      - Build new page as (changelog) for showing the new updates 
      - After 30 days:
              - Move the old BSI articles and linked UGA to archive
             - Delete the new page 
             - Update the modification date of the new BSI articles of the new Kompendium
