### ISSUE TITLE
update links when archiving

### ISSUE THREAD

**Issue by Multiflux** [CristoferSoler/Seel-17-18#9]

**Comment by circle-ish** [comment]
the problem:
- BSI catalogue article should have a "see also" section linking to non-catalogue articles (or similar)
- when the catalogue is updated and the old one pushed into the archive what happens to those links?

1) are non-catalogue articles which are specific to a catalogue version pushed into the archive as well?
2) how are existing non-catalogue articles linked to the new catalogue pages?
        - a tool compares new and old version and informs the mods responsible for the respective sections and they have to set the links anew by hand
